# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pandastudent

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5264f23f19d644eb896b381395350d44 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_35f31e6699e440319d091b30beee32c3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_5264f23f19d644eb896b381395350d44 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pandastudent'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a9de1fd4c29f4dcb82dc05b29401ad0e }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5264f23f19d644eb896b381395350d44 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'