# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pandastudent

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fff8c6817f954aafa272a6e2dca34624 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f392c82652f248d89c472d6c74c072fb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_fff8c6817f954aafa272a6e2dca34624 }}/anasasa:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pandastudent'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_460a3fa138d349b68ea9101c253ee9f2 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fff8c6817f954aafa272a6e2dca34624 }}/anasasa:${{ github.sha }}'